overcome csrf

diff --git a/giga-ci-chart/values.yaml b/giga-ci-chart/values.yaml
--- a/giga-ci-chart/values.yaml
+++ b/giga-ci-chart/values.yaml
@@ -11,6 +11,7 @@
 
 # For FQDN resolving of the controller service. Change this value to match your existing configuration.
 # ref: https://github.com/kubernetes/dns/blob/master/docs/specification.md
+
 jenkins:
   clusterZone: "cluster.local"
 
@@ -86,7 +87,9 @@ jenkins:
     #   - name: http_proxy
     #     value: "http://192.168.64.1:3128"
     # Set min/max heap here if needed with:
-    # javaOpts: "-Xms512m -Xmx512m"
+    javaOpts: 
+      -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout=180
+      -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
     # jenkinsOpts: ""
     # If you are using the ingress definitions provided by this chart via the `controller.ingress` block the configured hostname will be the ingress hostname starting with `https://` or `http://` depending on the `tls` configuration.
     # The Protocol can be overwritten by specifying `controller.jenkinsUrlProtocol`.
@@ -192,8 +195,8 @@ jenkins:
       - JNLP2-connect
     csrf:
       defaultCrumbIssuer:
-        enabled: true
-        proxyCompatability: true
+        enabled: false
+        proxyCompatability: false
     # Kubernetes service type for the JNLP agent service
     # agentListenerServiceType is the Kubernetes Service type for the JNLP agent service,
     # either 'LoadBalancer', 'NodePort', or 'ClusterIP'
@@ -221,8 +224,8 @@ jenkins:
     # loadBalancerIP: 1.2.3.4
     # Optionally configure a JMX port
     # requires additional javaOpts, ie
-    # javaOpts: >
-    #   -Dcom.sun.management.jmxremote.port=4000
+    # javaOpts: 
+    #   -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout=180
     #   -Dcom.sun.management.jmxremote.authenticate=false
     #   -Dcom.sun.management.jmxremote.ssl=false
     # jmxPort: 4000
@@ -233,10 +236,10 @@ jenkins:
 
     # List of plugins to be install during Jenkins controller start
     installPlugins:
-      - kubernetes:1.30.8
-      - pipeline-stage-step:2.2
+      - kubernetes:1.31.1
+      - pipeline-stage-step:2.5
       - m2release:0.14.0
-      - build-timeout:1.17
+      - build-timeout:1.17.1
       - ssh-credentials:1.19
       - postbuild-task:1.8
       - conditional-buildstep:1.3.5
@@ -245,107 +248,110 @@ jenkins:
       - workflow-api:2.47
       - Parameterized-Remote-Trigger:2.2.2
       - github-branch-source:2.0.1
-      - workflow-basic-steps:2.3
+      - workflow-basic-steps:2.11
       - antisamy-markup-formatter:1.5
       - ace-editor:1.1
+      - role-strategy:3.2.0
       - cvs:2.11
       - next-build-number:1.4
       - branch-api:2.6.4
-      - pipeline-rest-api:2.4
-      - pipeline-milestone-step:1.3
+      - pipeline-rest-api:2.10
+      - pipeline-milestone-step:1.3.1
       - slack:2.0.1
+      - caffeine-api:2.9.2-29.v717aac953ff3
       - workflow-cps:2.94
       - mapdb-api:1.0.9.0
       - ssh-slaves:1.9
       - sshd:3.1.0
       - workflow-durable-task-step:2.35
-      - cloudbees-folder:6.16
-      - pipeline-model-api:1.0
-      - workflow-aggregator:2.5
+      - cloudbees-folder:6.17
+      - pipeline-model-api:1.9.3
+      - workflow-aggregator:2.6
       - m2-repo-reaper:1.0
       - jquery-detached:1.2.1
       - rebuild:1.32
       - analysis-core:1.93
       - display-upstream-changes:0.1
-      - pipeline-stage-view:2.4
+      - pipeline-stage-view:2.10
       - build-token-root:1.4
-      - matrix-auth:1.1
+      - matrix-auth:3.0
       - extended-choice-parameter:0.75
-      - pam-auth:1.1
+      - pam-auth:1.6.1
       - workflow-step-api:2.24
       - translation:1.10
       - custom-tools-plugin:0.4.4
-      - git-client:2.7.6
+      - git-client:3.5.1
       - disk-usage:0.28
       - mail-watcher-plugin:1.16
-      - pipeline-build-step:2.4
-      - jsch:0.1.54.1
+      - pipeline-build-step:2.7
+      - jsch:0.1.55.2
       - authentication-tokens:1.4
       - flexible-publish:0.15.2
       - docker-commons:1.15
       - timestamper:1.8.8
-      - github-api:1.84
+      - github-api:1.301-378.v9807bd746da5
       - windows-slaves:1.0
       - github-organization-folder:1.6
       - handlebars:1.1.1
       - project-inheritance:2.0.0
-      - display-url-api:1.1.1
-      - durable-task:1.37
-      - workflow-cps-global-lib:2.5
+      - display-url-api:2.3.5
+      - durable-task:493.v195aefbb0ff2
+      - workflow-cps-global-lib:2.11
       - javadoc:1.1
-      - subversion:2.7.1
+      - subversion:2.15.1
       - pipeline-graph-analysis:1.1
-      - pipeline-model-definition:1.0
+      - pipeline-model-definition:1.3.2 
       - ws-cleanup:0.29
-      - pipeline-input-step:2.5
+      - pipeline-input-step:2.8
       - external-monitor-job:1.4
       - credentials-binding:1.27
-      - parameterized-trigger:2.35.2
-      - docker-workflow:1.9.1
-      - token-macro:2.3
+      - parameterized-trigger:2.36
+      - docker-workflow:1.14
+      - token-macro:267.vcdaea6462991
       - s3:0.10.6
-      - git:3.7.0
-      - apache-httpcomponents-client-4-api:4.5.5-3.0
+      - git:4.5.0
+      - apache-httpcomponents-client-4-api:4.5.10-2.0
       - URLSCM:1.6
       - thinBackup:1.9
       - multiple-scms:0.6
       - build-user-vars-plugin:1.5
-      - scm-api:2.6.4
+      - scm-api:2.6.5
       - plain-credentials:1.7
       - pipeline-github-lib:1.0
       - copyartifact:1.38
-      - pipeline-stage-tags-metadata:1.0
+      - pipeline-stage-tags-metadata:1.3.2
       - blame-upstream-commiters:1.2
       - uno-choice:2.0
       - jquery:1.11.2-0
-      - github:1.25.1
+      - github:1.34.1
       - junit:1.29
       - envinject:1.93.1
       - workflow-scm-step:2.13
       - build-name-setter:1.6.5
       - workflow-support:3.8
-      - git-server:1.7
+      - git-server:1.10
       - workflow-multibranch:2.26
       - bouncycastle-api:2.25
       - global-variable-string-parameter:1.2
-      - script-security:1.77
+      - script-security:1.78
+      - strict-crumb-issuer:2.1.0
       - jenkins-multijob-plugin:1.21
       - jobConfigHistory:2.14
       - ant:1.2
-      - credentials:2.6.1
+      - credentials:1055.v1346ba467ba1
       - momentjs:1.1.1
       - aws-java-sdk:1.10.50
       - dependency-check-jenkins-plugin:3.1.0
       - structs:1.23
-      - mailer:1.19
+      - mailer:1.34
       - http_request:1.8.11
       - build-blocker-plugin:1.7.3
-      - pipeline-model-declarative-agent:1.0
+      - pipeline-model-declarative-agent:1.1.1
       - workflow-job:2.41
       - ansicolor:0.5.0
       - matrix-project:1.18
       - run-condition:1.0
-      - authorize-project:1.2.2
+      - authorize-project:1.4.0
       - email-ext:2.44
       - jackson2-api:2.13.0-230.v59243c64b0a5
       - git-parameter:0.9.1
@@ -354,6 +360,12 @@ jenkins:
       - job-dsl:1.78.1
       - trilead-api:1.0.13
       - parameter-separator:1.3
+      - command-launcher:1.6
+      - jdk-tool:1.5
+      - jaxb:2.3.0.1
+      - configuration-as-code-support:1.17
+      
+      
     # Set to false to download the minimum required version of all dependencies.
     installLatestPlugins: true
 
@@ -454,6 +466,11 @@ jenkins:
               system:
                 domainCredentials:
                   - credentials:
+                      - usernamePassword:
+                            scope: SYSTEM
+                            id: oren
+                            username: admin
+                            password: GigaSpaces
                       - basicSSHUserPrivateKey:
                             scope: GLOBAL
                             id: git_credentials_id
@@ -515,16 +532,35 @@ jenkins:
                                   -----END RSA PRIVATE KEY-----
             jenkins:
               authorizationStrategy:
-                globalMatrix:
-                  grantedPermissions:
-                    - "Overall/Read:anonymous"
-                    - "Job/Read:anonymous"
-                    - "View/Read:anonymous"
-                    - "Overall/Administer:authenticated"
+                roleBased:
+                  roles:
+                    global:
+                      - name: "admin"
+                        description: "Jenkins administrators"
+                        permissions:
+                          - "Overall/Administer"
+                        assignments:
+                          - "admin"
+                      - name: "readonly"
+                        description: "Read-only users"
+                        permissions:
+                          - "Overall/Read"
+                          - "Job/Read"
+                        assignments:
+                          - "authenticated"
+              securityRealm:
+                local:
+                  allowsSignup: false
+                  users:
+                    - id: "admin"
+                      password: "GigaSpaces"
+                    - id: "sultan"
+                      password: "1234"
               crumbIssuer:
                 strict:
-                  checkSessionMatch: false
-                  xorMasking: false    
+                  hoursValid: 5
+                  checkSessionMatch: true
+                  xorMasking: false
               agentProtocols:
               - "JNLP4-connect"
               - "Ping"        
@@ -705,7 +741,7 @@ jenkins:
                           }
                       }
                   }
-                  X    
+                  
                       
                 
                     
@@ -1257,3 +1293,246 @@ jenkins:
       - name: ""
         securityGroupIds: []
         podSelector: {}
+
+nexus-repository-manager:
+  nexus:
+    
+    properties:
+      override: true
+      data:
+        nexus.scripts.allowCreation: true
+    env:
+      - name: ENABLE_ANONYMOUS_ACCESS
+        value : "false"
+      - name: NEXUS_SECURITY_RANDOMPASSWORD
+        value: "false"
+  deployment:
+    
+    initContainers:
+    - name: fmp-volume-permission
+      image: busybox
+      imagePullPolicy: IfNotPresent
+      command: ['cp','/sonatype-nexus-conf/postStart.sh', '/scripts/postStart.sh']
+      volumeMounts:
+      - mountPath: /nexus-data
+        name: nexus-repository-manager-data
+      - mountPath: /sonatype-nexus-conf
+        name:  nexus-repository-manager-conf
+      - mountPath: /scripts  
+        name: scripts
+    - name: run-script
+      image: busybox
+      imagePullPolicy: IfNotPresent
+      command: ['chmod','777','/scripts/postStart.sh']
+      volumeMounts:
+      - mountPath: /nexus-data
+        name: nexus-repository-manager-data
+      - mountPath: /sonatype-nexus-conf
+        name:  nexus-repository-manager-conf
+      - mountPath: /scripts  
+        name: scripts
+    # Uncomment and modify this to run a command after starting the nexus container.
+    
+    additionalVolumes:
+    - name: scripts
+      emptyDir: {}
+    additionalVolumeMounts: 
+    - name : scripts
+      mountPath:  /scripts
+    
+        
+    # preStart:
+    #   command:
+        
+    #     - ['chown','-R', '777', '/nexus-data']
+    #   - '["/bin/rm", "-f", "/nexus-data/lock"]'
+      
+    postStart:
+      command:
+      -   /scripts/postStart.sh
+  secret:
+    enabled: true
+    mountPath: '/nexus-data/config'
+    readOnly: true
+    data: 
+      password : |
+        R2lnYVNwYWNlcw==
+
+  service:
+    name: nexus3
+    enabled: true
+    labels: {}
+    annotations: {}
+    type: ClusterIP
+
+
+  config:
+    enabled: true
+    data:
+      OpenSpacesmaven.json: |-
+        {
+          "name": "OpenSpaces",
+          "online": true,
+          "storage": {
+            "blobStoreName": "default",
+            "strictContentTypeValidation": true
+          },
+          "cleanup": {
+            "policyNames": [
+              "string"
+            ]
+          },
+          "proxy": {
+            "remoteUrl": "http://maven-repository.openspaces.org",
+            "contentMaxAge": 1440,
+            "metadataMaxAge": 1440
+          },
+          "negativeCache": {
+            "enabled": true,
+            "timeToLive": 1440
+          },
+          "httpClient": {
+            "blocked": false,
+            "autoBlock": true,
+            "connection": {
+              "retries": 0,
+              "userAgentSuffix": "string",
+              "timeout": 60,
+              "enableCircularRedirects": false,
+              "enableCookies": false,
+              "useTrustStore": false
+            },
+            "authentication": {
+              "type": "username",
+              "username": "string",
+              "password": "string",
+              "ntlmHost": "string",
+              "ntlmDomain": "string",
+              "preemptive": false
+            }
+          },
+          "routingRule": "string",
+          "maven": {
+            "versionPolicy": "MIXED",
+            "layoutPolicy": "STRICT",
+            "contentDisposition": "ATTACHMENT"
+          }
+        }
+      muledepsmaven.json: |-
+        {
+          "name": "mule-deps",
+          "online": true,
+          "storage": {
+            "blobStoreName": "default",
+            "strictContentTypeValidation": true
+          },
+          "proxy": {
+            "remoteUrl": "https://repository.mulesoft.org/nexus/content/repositories/public",
+            "contentMaxAge": -1,
+            "metadataMaxAge": 1440
+          },
+          "negativeCache": {
+            "enabled": true,
+            "timeToLive": 1440
+          },
+          "httpClient": {
+            "blocked": false,
+            "autoBlock": true
+          },
+          "maven": {
+            "versionPolicy": "RELEASE",
+            "layoutPolicy": "STRICT"
+          }
+        }
+      group.json: |-
+        {
+          "name": "maven-public",
+          "format": "maven2",
+          "url": "http://localhost:8081/repository/maven-public",
+          "online": true,
+          "storage": {
+            "blobStoreName": "default",
+            "strictContentTypeValidation": true
+          },
+          "group": {
+            "memberNames": [
+              "mule-deps",
+              "OpenSpaces",
+              "maven-central",
+              "maven-releases",
+              "maven-snapshots"
+            ]
+          },
+          "type": "group"
+        }
+      postStart.sh: |-
+        #!/bin/bash
+        set -eu
+        HOST="localhost:8081"
+        until curl --output /dev/null --silent --head --fail http://${HOST}/; do
+        printf ‘.’
+        sleep 5
+        done
+        NEXUS_BASE_DIR="/sonatype-nexus-conf"
+        USERNAME="admin"
+        PASSWORD=admin123
+        PASSWORD_FROM_FILE="$(cat /nexus-data/config/password   || true)"
+        function die() {
+          echo "ERROR: $*" 1>&2
+          exit 1
+        }
+        # Call the Nexus API for the specified repository
+        function runCurlFromJsonFile() {
+            local jsonFile
+            local service
+            local body
+            local method
+            jsonFile="${1}"
+            service="${2}"
+            method="${3}"
+            body="$(cat "${jsonFile}")"
+            if  ! curl --fail -X "${method}" -u "${USERNAME}":"${PASSWORD}" "http://${HOST}/${service}" -H "accept:application/json" -H "Content-Type:application/json" -d "${body//[$‘\t\r\n’]}"; then
+                echo "Error calling Nexus API for http://${HOST}/${service} to add repository from ${jsonFile}"
+            fi
+        }
+        function setPasswordFromFile() {
+            if [ -n "${PASSWORD_FROM_FILE}" ]; then
+                echo "Updating PASSWORD variable from password file."
+                PASSWORD="${PASSWORD_FROM_FILE}"
+            else
+                echo "Not updating PASSWORD var. Password file either non-existent or not readable."
+            fi
+        }
+
+        if curl --fail --silent -u "${USERNAME}":"${PASSWORD}" http://"${HOST}"/service/metrics/ping; then
+            echo "Login to nexus succeeded. Default password worked. Updating password if available..."
+            curl --fail -X PUT -u "${USERNAME}":"${PASSWORD}" "http://${HOST}/service/rest/beta/security/users/admin/change-password" --header "Content-Type: text/plain" -d "${PASSWORD_FROM_FILE}"
+            setPasswordFromFile
+        elif [ -n "${PASSWORD_FROM_FILE}" ]; then
+            setPasswordFromFile
+            echo "Default password failed. Checking password file..."
+            if curl --fail --silent -u "${USERNAME}":"${PASSWORD}" http://"${HOST}"/service/metrics/ping; then
+                echo "Login to nexus succeeded. Password from secret file worked."
+            else
+                die "Login to nexus failed. Tried both the default password and the provided password secret file."
+            fi
+        else
+            die "Login to nexus failed. Tried the default password only since no password secret file was provided."
+        fi
+        # For each maven repository proxy json file, create the repo proxy via the Nexus API.
+        echo "Creating maven proxy repositories from json"
+        mapfile -t REPOS < <(find "${NEXUS_BASE_DIR}"  -type f -name "*maven.json*")
+        for repo in "${REPOS[@]}"; do
+            runCurlFromJsonFile "${repo}" "service/rest/v1/repositories/maven/proxy" POST
+        done
+        # For each maven group repository json file, create the repo via the Nexus API.
+
+        echo "Creating maven group repositories from json"
+
+        mapfile -t REPOS < <(find "${NEXUS_BASE_DIR}"  -type f -name "*group.json*")
+
+        for repo in "${REPOS[@]}"; do
+            runCurlFromJsonFile "${repo}" "service/rest/v1/repositories/maven/group/" POST
+        
+        
+        done
diff --git a/nexus/values.yaml b/nexus/values.yaml
--- a/nexus/values.yaml
+++ b/nexus/values.yaml
@@ -7,7 +7,7 @@ nexus:
       nexus.scripts.allowCreation: true
   env:
     - name: NEXUS_SECURITY_RANDOMPASSWORD
-      value: "false"
+      value: "true"
 deployment:
   
   initContainers:
@@ -41,7 +41,7 @@ deployment:
   additionalVolumeMounts: 
   - name : scripts
     mountPath:  /scripts
-
+  
       
   # preStart:
   #   command:
@@ -49,51 +49,147 @@ deployment:
   #     - ['chown','-R', '777', '/nexus-data']
   #   - '["/bin/rm", "-f", "/nexus-data/lock"]'
     
-  # postStart:
-  #   command:  
+  postStart:
+    command:  
 
-  #   - /script/postStart.sh
+    -  /scripts/postStart.sh
+secret:
+  enabled: true
+  mountPath: '/nexus-data/config/'
+  readOnly: true
+  data: 
+    password : |
+      R2lnYVNwYWNlcw==
+
+service:
+  name: nexus3
+  enabled: true
+  labels: {}
+  annotations: {}
+  type: ClusterIP
+
 
 config:
   enabled: true
   data:
-    maven.json: |-
+    OpenSpacesmaven.json: |-
       {
-          "name": "maven-jenkinsci",
-          "online": true,
-          "storage": {
-            "blobStoreName": "default",
-            "strictContentTypeValidation": true
+        "name": "OpenSpaces",
+        "online": true,
+        "storage": {
+          "blobStoreName": "default",
+          "strictContentTypeValidation": true
+        },
+        "cleanup": {
+          "policyNames": [
+            "string"
+          ]
+        },
+        "proxy": {
+          "remoteUrl": "http://maven-repository.openspaces.org",
+          "contentMaxAge": 1440,
+          "metadataMaxAge": 1440
+        },
+        "negativeCache": {
+          "enabled": true,
+          "timeToLive": 1440
+        },
+        "httpClient": {
+          "blocked": false,
+          "autoBlock": true,
+          "connection": {
+            "retries": 0,
+            "userAgentSuffix": "string",
+            "timeout": 60,
+            "enableCircularRedirects": false,
+            "enableCookies": false,
+            "useTrustStore": false
           },
-          "proxy": {
-            "remoteUrl": "https://repo.jenkins-ci.org/releases/",
-            "contentMaxAge": -1,
-            "metadataMaxAge": 1440
-          },
-          "negativeCache": {
-            "enabled": true,
-            "timeToLive": 1440
-          },
-          "httpClient": {
-            "blocked": false,
-            "autoBlock": true
-          },
-          "maven": {
-            "versionPolicy": "RELEASE",
-            "layoutPolicy": "STRICT"
+          "authentication": {
+            "type": "username",
+            "username": "string",
+            "password": "string",
+            "ntlmHost": "string",
+            "ntlmDomain": "string",
+            "preemptive": false
           }
+        },
+        "routingRule": "string",
+        "maven": {
+          "versionPolicy": "MIXED",
+          "layoutPolicy": "STRICT",
+          "contentDisposition": "ATTACHMENT"
         }
+      }
+    muledepsmaven.json: |-
+      {
+        "name": "mule-deps",
+        "online": true,
+        "storage": {
+          "blobStoreName": "default",
+          "strictContentTypeValidation": true
+        },
+        "cleanup": {
+          "policyNames": [
+            "string"
+          ]
+        },
+        "proxy": {
+          "remoteUrl": "https://repository.mulesoft.org/nexus/content/repositories/public",
+          "contentMaxAge": 1440,
+          "metadataMaxAge": 1440
+        },
+        "negativeCache": {
+          "enabled": true,
+          "timeToLive": 1440
+        },
+        "httpClient": {
+          "blocked": false,
+          "autoBlock": true,
+          "connection": {
+            "retries": 0,
+            "userAgentSuffix": "string",
+            "timeout": 60,
+            "enableCircularRedirects": false,
+            "enableCookies": false,
+            "useTrustStore": false
+          },
+          "authentication": {
+            "type": "username",
+            "username": "string",
+            "password": "string",
+            "ntlmHost": "string",
+            "ntlmDomain": "string",
+            "preemptive": false
+          }
+        },
+        "routingRule": "string",
+        "maven": {
+          "versionPolicy": "MIXED",
+          "layoutPolicy": "STRICT",
+          "contentDisposition": "ATTACHMENT"
+        }
+      }
     group.json: |-
       {
-          "name": "maven-group",
-          "online": true,
-          "storage": {
-            "blobStoreName": "default",
-            "strictContentTypeValidation": true
-          },
-          "group": {
-            "memberNames": ["maven-public","maven-central", "maven-releases", "maven-jenkinsci"]
-          }
+        "name": "maven-public",
+        "format": "maven2",
+        "url": "http://localhost:8081/repository/maven-public",
+        "online": true,
+        "storage": {
+          "blobStoreName": "default",
+          "strictContentTypeValidation": true
+        },
+        "group": {
+          "memberNames": [
+            "mule-deps",
+            "OpenSpaces",
+            "maven-central",
+            "maven-releases",
+            "maven-snapshots"
+          ]
+        },
+        "type": "group"
       }
     postStart.sh: |-
       #!/bin/bash
@@ -105,7 +201,8 @@ config:
       done
       NEXUS_BASE_DIR="/sonatype-nexus-conf"
       USERNAME="admin"
-      PASSWORD=$(cat /nexus-data/admin.password)
+      PASSWORD=admin123
+      PASSWORD_FROM_FILE="$(cat /nexus-data/config/password || true)"
       function die() {
         echo "ERROR: $*" 1>&2
         exit 1
@@ -121,22 +218,51 @@ config:
       method="${3}"
       body="$(cat "${jsonFile}")"
       if  ! curl --fail -X "${method}" -u "${USERNAME}":"${PASSWORD}" "http://${HOST}/${service}" -H "accept:application/json" -H "Content-Type:application/json" -d "${body//[$‘\t\r\n’]}"; then
-          echo "Error calling Nexus API for http://${HOST}/${service} to add repository from ${jsonFile}"
+      echo "Error calling Nexus API for http://${HOST}/${service} to add repository from ${jsonFile}"
       fi
       }
+      
+      
+      function setPasswordFromFile() {
+      if [ -n "${PASSWORD_FROM_FILE}" ]; then
+          echo "Updating PASSWORD variable from password file."
+          PASSWORD="${PASSWORD_FROM_FILE}"
+      else
+          echo "Not updating PASSWORD var. Password file either non-existent or not readable."
+      fi
+      }
+
+      if curl --fail --silent -u "${USERNAME}":"${PASSWORD}" http://"${HOST}"/service/metrics/ping; then
+          echo "Login to nexus succeeded. Default password worked. Updating password if available..."
+          curl --fail -X PUT -u "${USERNAME}":"${PASSWORD}" "http://${HOST}/service/rest/beta/security/users/admin/change-password" --header "Content-Type: text/plain" -d "${PASSWORD_FROM_FILE}"
+          setPasswordFromFile
+      elif [ -n "${PASSWORD_FROM_FILE}" ]; then
+          setPasswordFromFile
+          echo "Default password failed. Checking password file..."
+          if curl --fail --silent -u "${USERNAME}":"${PASSWORD}" http://"${HOST}"/service/metrics/ping; then
+              echo "Login to nexus succeeded. Password from secret file worked."
+          else
+              die "Login to nexus failed. Tried both the default password and the provided password secret file."
+          fi
+      else
+          die "Login to nexus failed. Tried the default password only since no password secret file was provided."
+      fi 
+
       # For each maven repository proxy json file, create the repo proxy via the Nexus API.
       echo "Creating maven proxy repositories from json"
-      mapfile -t REPOS < <(find "${NEXUS_BASE_DIR}" -maxdepth 1 -type f -name "*maven.json*")
+      mapfile -t REPOS < <(find "${NEXUS_BASE_DIR}"   -type f -name "*maven.json*")
       for repo in "${REPOS[@]}"; do
-          runCurlFromJsonFile "${repo}" "service/rest/beta/repositories/maven/proxy" POST
+          runCurlFromJsonFile "${repo}" "service/rest/v1/repositories/maven/proxy" POST
+         
       done
+
       # For each maven group repository json file, create the repo via the Nexus API.
-      
+
       echo "Creating maven group repositories from json"
-      
-      mapfile -t REPOS < <(find "${NEXUS_BASE_DIR}" -maxdepth 1 -type f -name "*group.json*")
-      
+
+      mapfile -t REPOS < <(find "${NEXUS_BASE_DIR}"   -type f -name "*group.json*")
+
       for repo in "${REPOS[@]}"; do
-          runCurlFromJsonFile "${repo}" "service/rest/beta/repositories/maven/group" POST
+      runCurlFromJsonFile "${repo}" "service/rest/v1/repositories/maven/group/" POST
+      
       done
-      sleep 3000
